### ISSUE TITLE
USER STORY <Acceptance criteria>

### ISSUE THREAD

**Issue by mvv1790** [mvv1790/Agile_Project_1#6]
As a **role** I can **capability** so that **received benefit**

Acceptance Criteria 1: The distance of the run

Acceptance Criteria 2: Suitable route for individual runners

Acceptance Criteria 3: Challenge of the route (elevation, urban or cross-country)   

#Tasks

- [ ] Allow participants to submit answers and show anonymously if desired
- [ ] Let participants decide on an optimal run distances
- [ ] Update the view, include a checkbox
